#!/usr/bin/env python
import subprocess, re, sys
from subprocess import *

print 'Searching for flash videos...'
print '(Please make sure the video is completely buffered before running)'

if len(sys.argv) < 2:
	filename = 'video.flv'
else:
	filename = sys.argv[1]

# Regex to parse lsof string
parse = re.compile('chromium- ([0-9]+).+?([0-9]+).+,.+ .+ .+/tmp/Flash.+ \(deleted\)')

# Get the pids for the web browser
pidof = Popen(['pidof', 'chromium-browser'], stdout=PIPE)
pids = pidof.communicate()[0][:-1].split(' ')

# Run lsof, find all files attached to chromium*
lsof =  Popen(['lsof', '-c', 'chromium-'], stdout=PIPE)

# Grep the results we actually want out, this is a bit redundent with the regex
grep =  Popen(['grep', 'Flash'], stdin=lsof.stdout, stdout=PIPE)

# Processes is the stdout from grep
processes = grep.communicate()[0]

# Regex out all the data we cat about
try:
	video = parse.findall(processes)[0]
except IndexError:
	print 'No flash videos found'
	sys.exit()

# Find the processes folder in /proc/ with the dettached file handle and cat it
cat = Popen(['cat', '/proc/' + video[0] + '/fd/' + video[1]], stdout=PIPE)

# Redirect stdout to a video file
file = open(filename, 'w')
file.write(cat.communicate()[0])
file.close()

print 'Video saved to %s' % filename
